public enum TokenType {
    INT_LIT,FLOAT_LIT,IDENTIFIER,
    PLUS,MINUS,TIMES,DIVIDE,MODULO,KEYWORD,AND,OR,
    ASSIGNMENT_OPERATOR,SEMICOLON,LEFT_PARENTHESIS,RIGHT_PARENTHESIS,EQUAL,LESS_OR_EQUALS, GREATER_OR_EQUALS, GREATER_THAN, LESS_THAN, 
    EOF, STRING, 
}
